### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by shelcia** [shelcia/Bloggram#449]

**Comment by nepalivai** [comment]
Can I work on this issue? Here is a link to my [previous work.](https://www.instagram.com/cooolmonkeydesigner/)

**Comment by aindree-2005** [comment]
![bloggram](https://github.com/shelcia/Bloggram/assets/68018372/1039eb0d-24d9-4366-a5c6-a7a8bea2ea7c)

@shelcia how is this logo?

**Comment by shelcia** [comment]
Make sure it sticks with the theme of the website like the colors typography

**Comment by aindree-2005** [comment]
![bloggram-new](https://github.com/shelcia/Bloggram/assets/68018372/a90819b0-cfbd-489f-a682-a23f1dc81fd6)
@shelcia is this better? It is more in sync with the website design but eye catching as a standalone logo. I can add the png and .ico files and create a PR if this is ok

**Comment by shelcia** [comment]
sure go ahead
