### ISSUE TITLE
Adding Some Valdition To Form Would Be Good

### ISSUE THREAD

**Issue by Ayusht777** [shelcia/Bloggram#474]
I want to implement validation for my sign-up form, ensuring that the name field only accepts letters and doesn't allow special symbols or numbers. I also want a distinct field for the username, allowing special characters and numbers.

**Comment by Ayusht777** [comment]
I've made updates to the login page, specifically adding name validation and a password field with an eye icon for toggling visibility
![image](https://github.com/shelcia/Bloggram/assets/106388215/fdaa3730-2d08-4a3e-849d-806db30a869b)
if you good with it then will create a pull Request

**Comment by shelcia** [comment]
sure it works
